### ISSUE TITLE
maximize button not working

### ISSUE THREAD

**Issue by neuronflow** [ich777/docker-krusader#3]
the maximize button is blacked out and dysfunctional

<img width="1359" alt="Screenshot 2024-11-30 at 11 25 19" src="https://github.com/user-attachments/assets/958247a8-6b5e-4b36-a726-c40b2bc88211">

**Comment by ich777** [comment]
The maximize button is not shown because the application should start in full screen by default. Have you tried to restart the container already?

**Comment by neuronflow** [comment]
yes I restarted the container several times.

**Comment by ich777** [comment]
I‘ll look into that but this is the first time that I see this.
Please try to click on the little arrow in the left corner, then on the gear icon and at scaling select server side scaling.

**Comment by neuronflow** [comment]
sorry, can't follow. which arrow in which left corner?

**Comment by neuronflow** [comment]
do you mean the no vnc overlay?

currently it is set to "remote resizing".

**Comment by neuronflow** [comment]
<img width="1728" alt="Screenshot 2024-11-30 at 13 13 06" src="https://github.com/user-attachments/assets/397bba25-254e-463b-937c-d639eb7d8b03">

**Comment by ich777** [comment]
Sorry but I can't reproduce this over here...
![Peek 2024-11-30 15-33](https://github.com/user-attachments/assets/94f9f0c6-5280-4199-8028-707e0db3a76b)


However this was with non root mode, in root mode I can reproduce the behaviour, however you should be able to resize the window on the lower right corner:
![Peek 2024-11-30 15-37](https://github.com/user-attachments/assets/838ac53a-3add-4b0f-9ea0-29d2a3b3428e)

**Comment by ich777** [comment]
I will look a bit more into that but that will take me some time, thanks for reporting that.

**Comment by ich777** [comment]
I've pushed a update to the container and it should now work:
![Peek 2024-11-30 15-51](https://github.com/user-attachments/assets/0fb29ac8-b19b-43e6-91a4-6dae9281016b)

Please update the container itself (Go to the Docker page, enable Advanced View on the top right corner, click `force update` at Krusader, don't forget to disable Advanced View after updating Krusader).

**Comment by CyberBlaed** [comment]
I appear to have this same issue, and cannot diagnose what the issue is, it seems to be presented with the recent changes within the past 48hrs.
(as I was using Kruusader to move from server to server and hand easy window management) now it appears locked in place)

i reset the unraid template, turned off remote scaling "NOVNC_RESIZE" and still does not resolve it. so Op is not alone on this issue, however we can see in your post there, you can move it around no issue.

so;

1) mine is a fresh krusader from last year, no issue.
2) updated today to the new one, and this 'window size' issue is presented.
3) changed set resolutions of the unraid template to bigger 1080p hoping to resolve it. no luck.
3) tried the force update function like you suggested, did not resolve it.

oddly, when continuing my file copying, the file copy (percentage done window) is fully maximum to my screen now..
I can shrink it, but it is locked to the first top left pixel of my screen and cannot move it.... 
thus it appears the ... window manager(titlebar of app) is maybe the issue? (as the Krusader app is basically LOCKED in place, however bottom right corner, will stretch window out to the right and shrink. i however cannot move the window itself)

as of right now, despite the forced update, no solution as of this post.
```
Pulling image: ich777/krusader:latest

IMAGE ID [1589837787]: Pulling from ich777/krusader.
Status: Image is up to date for ich777/krusader:latest

TOTAL DATA PULLED: 0 B

The command finished successfully!
```
Example screenshot of file copy/browser is firefox.
![Screenshot 2024-12-02 at 12 42 48 pm](https://github.com/user-attachments/assets/45be86e8-c65e-43f9-bc01-f849a5248980)

**Comment by ich777** [comment]
@CyberBlaed this is not the same issue, I did that on purpose but now I've reverted the change since it seems to cause more trouble then it was before, please update the container itself and it will be fixed and reverted back to normal.

**Comment by ich777** [comment]
@neuronflow I close this issue now since I have now tried a few things and you can maximize the window in the Taskbar:
![Peek 2024-12-02 07-17](https://github.com/user-attachments/assets/406390ef-6dd3-4f10-b52f-d0fe06ca4b40)

**Comment by neuronflow** [comment]
I am not happy with closing the issue, your screenshot above shows it. 
I appreciate that you provide a workaround though :)

**Comment by ich777** [comment]
@neuronflow usually I don't close issues that easy but this change will cause confusion for many existing users and will leave it as is.
BTW, Krusader should save the position from the window.

**Comment by neuronflow** [comment]
why does the binhex crusader have the buttons?

**Comment by ich777** [comment]
Because he implemented them and I never intended them to be used in the first place.
Sorry but I won't change that.
